//
//  TimeBlock.swift
//  Nudge
//
//  A scheduled block of time tied to a task. Generated by the Claude API
//  when converting a task list into a daily/weekly schedule.
//  Never rename existing fields — add new ones instead.
//

import Foundation
import SwiftData

@Model
final class TimeBlock {
    var id: UUID
    var taskId: UUID?               // links to the NudgeTask this block is for
    var label: String               // display title — may differ from task title
    var startTime: Date
    var endTime: Date
    var category: String            // "school" | "work" | "health" | "personal" | "break" | "prep"
    var notes: String?              // optional context from Claude
    var isCompleted: Bool
    var createdAt: Date
    var flexibility: String          // "fixed" | "flexible" | "ai_decides"

    init(
        id: UUID = UUID(),
        taskId: UUID? = nil,
        label: String,
        startTime: Date,
        endTime: Date,
        category: String = "personal",
        notes: String? = nil,
        isCompleted: Bool = false,
        createdAt: Date = Date(),
        flexibility: String = "flexible"
    ) {
        self.id = id
        self.taskId = taskId
        self.label = label
        self.startTime = startTime
        self.endTime = endTime
        self.category = category
        self.notes = notes
        self.isCompleted = isCompleted
        self.createdAt = createdAt
        self.flexibility = flexibility
    }

    /// Duration of this block in minutes
    var durationMinutes: Int {
        Int(endTime.timeIntervalSince(startTime) / 60)
    }
}
